[package]
name = "brix_processor"
version = "0.1.0"
authors = ["Miapolis <41233357+Miapolis@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinytemplate = "1.2.1"
serde = { version = "1.0.126", features = ["derive"] }
# serde_yaml = "0.8.17"
